name: Deploy to DigitalOcean Functions

on:
  push:
    branches:
      - digitalocean-function

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install doctl
        run: |
          sudo snap install doctl

      - name: Authenticate with DigitalOcean
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        run: |
          doctl auth init -t $DIGITALOCEAN_ACCESS_TOKEN

      - name: Connect to DigitalOcean Functions Namespace
        run: |
          doctl serverless connect domain-checker-function

      - name: Clean previous deployment
        run: rm -rf .deployed

      - name: Deploy to DigitalOcean Functions
        run: |
          doctl serverless deploy .
